# Generated by Django 2.2.1 on 2019-07-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenges',
            old_name='challenge_name',
            new_name='challengename',
        ),
    ]
