# Generated by Django 2.2.1 on 2019-07-24 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_auto_20190722_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenges',
            old_name='challengename',
            new_name='challenge_name',
        ),
        migrations.AddField(
            model_name='challenges',
            name='challenge_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
