# Generated by Django 2.2.1 on 2019-07-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_auto_20190724_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='challenge_path',
            field=models.CharField(max_length=1000),
        ),
    ]
