# Generated by Django 2.2.1 on 2019-08-01 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0004_auto_20190724_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchallenges',
            old_name='end_date',
            new_name='start_date',
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('reply', models.CharField(max_length=1000)),
                ('challenges', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='challenges.Challenges')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
