# Generated by Django 2.2.1 on 2019-08-01 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_auto_20190801_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='challenges',
            new_name='challen',
        ),
    ]
