# Generated by Django 2.2.1 on 2019-08-02 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_auto_20190801_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='challen',
            new_name='challenges',
        ),
    ]
