# Generated by Django 2.2.1 on 2019-07-18 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190718_1737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
