# Generated by Django 2.2.1 on 2019-08-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='framework',
        ),
    ]
