# Generated by Django 2.2.1 on 2019-08-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_skill_tools'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tools',
            new_name='Tool',
        ),
    ]
